### PR TITLE
feat/first release

### PR DESCRIPTION
**Pull request by RafaelGSS**

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
looking good. let's keep everything in this PR until we're happy then we merge it when the rewrite of the blog post is complete

**Comment by RafaelGSS** [comment]
> looking good. let's keep everything in this PR until we're happy then we merge it when the rewrite of the blog post is complete

Roger that.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by RafaelGSS** [comment]
@mcollina Let's discuss here the benchmarks (It's way better to be notified and keep an ongoing conversation).

Here are the results that I got from a AWS T2.XLARGE:

**node 01-simplest-express.js**:

image

**node 02-express-bunyan.js**:

image

**node 03-express-winston.js**:

image

**node 04-express-pino.js**:

image


**node 04-1-express-pino.js** (this file was created only to show the performance gains on doing manual logging (without several of the serializer):

image

---

Note: I have tested through v12 until v16 and all versions are consistent with their values.

Also, is worth it mentioning that adding a custom logger with asynchronous logging doesn't change the throughput as you expect

```js
const pino = require('pino')
const dest = pino.destination({ sync: false }) // logs to stdout with no args
const logger = pino(dest)

app.use(require('express-pino-logger')({ logger }))

// same benchmark results to

const pino = require('pino')

app.use(require('express-pino-logger')({ extreme: true }))
```

I'm missing something?

**Comment by mcollina** [comment]
Where are you directing stdout? You need to log to a file. If not the TTY (your shell) will be the most problematic.

Do not use T-line AWS machines as they have burst performance and the results are non comparable. Use the M-line machines or a dedicated machine (your laptop should be ok).

I can also run them on my dedicated server if you script everything/ one command.

---

Also do another test at 60 seconds with 10 pipelined connections... and you should see winston degrading further.
Increase the number of connections/

**Comment by RafaelGSS** [comment]
Latest results

image

--- 

Also, I have created a script (`benchmark.js`) to run all benchmarks, could you check in your dedicated machine? @mcollina 

`node benchmark.js && cat result.md`

**Comment by mcollina** [comment]
I've just released pino-http@6.5.0. - this will need updating.

**Comment by RafaelGSS** [comment]
Now I'm writing the section on Asynchronous Loggin and I did comparisons between async x sync and the results were closest, is that expected?

script: 
```js
'use strict'

const app = require('express')()

const pino = require('pino')
const dest = pino.destination({ sync: false, dest: '/tmp/test.log' })
const logger = pino(dest)

function main() {
  app.use(require('express-pino-logger')({ logger }))

  app.get('/', function (req, res) {
    res.send('hello world')
  })

  return app.listen(3000)
}

main()
```

```diff
- const dest = pino.destination({ sync: false, dest: '/tmp/test.log' })
+ const dest = pino.destination({ sync: true, dest: '/tmp/test.log' })
```

image

**Comment by mcollina** [comment]
> Now I'm writing the section on Asynchronous Loggin and I did comparisons between async x sync and the results were closest, is that expected?

Yes. You can try writing to stdout for both, you should be able to see the difference.

**Comment by RafaelGSS** [comment]
Updated! The document is now ready to review @simoneb @mcollina.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
